

export const livros = [
        {nome: 'Alfabeto', id: 1, src:'https://lebiscuit.vtexassets.com/arquivos/ids/2939859/LIVRO-INF-TODOLIVRO-APRENDENDO-ALFABETO.jpg?v=638247353730500000'},
        {"nome": "Aventuras na Floresta", "id": 2, "src": "https://images-na.ssl-images-amazon.com/images/I/81-9Zm7vH9L.jpg"},
        {"nome": "Histórias do Mar", "id": 3, "src": "https://images-na.ssl-images-amazon.com/images/I/71FXWMTUX7L.jpg"},
        {"nome": "Contos de Fadas", "id": 4, "src": "https://images-na.ssl-images-amazon.com/images/I/91HHxxtA1wL.jpg"},
        {"nome": "Matemática Divertida", "id": 5, "src": "https://images-na.ssl-images-amazon.com/images/I/91bYsX41DVL.jpg"},
        {"nome": "O Mundo dos Dinossauros", "id": 6, "src": "https://images-na.ssl-images-amazon.com/images/I/81kAwnAh4oL.jpg"},
        {"nome": "Viagem ao Espaço", "id": 7, "src": "https://images-na.ssl-images-amazon.com/images/I/71YNk8gHbbL.jpg"},
        {"nome": "Aventuras no Deserto", "id": 8, "src": "https://images-na.ssl-images-amazon.com/images/I/71KilybDOoL.jpg"},
        {"nome": "Histórias da Selva", "id": 9, "src": "https://images-na.ssl-images-amazon.com/images/I/91UqrwK8dHL.jpg"},
        {"nome": "Contos do Futuro", "id": 10, "src": "https://images-na.ssl-images-amazon.com/images/I/81-QB7nDh4L.jpg"},
        {"nome": "Ciências Divertidas", "id": 11, "src": "https://images-na.ssl-images-amazon.com/images/I/71aLultW5EL.jpg"},
        {"nome": "Animais Fantásticos", "id": 12, "src": "https://images-na.ssl-images-amazon.com/images/I/81eB+7+CkUL.jpg"},
        {"nome": "Histórias do Espaço", "id": 13, "src": "https://images-na.ssl-images-amazon.com/images/I/71KilybDOoL.jpg"},
        {"nome": "Viagem ao Fundo do Mar", "id": 14, "src": "https://images-na.ssl-images-amazon.com/images/I/81t2CVWEsUL.jpg"},
        {"nome": "Matemática para Crianças", "id": 15, "src": "https://images-na.ssl-images-amazon.com/images/I/81FxtjLK-1L.jpg"},
        {"nome": "Segredos da Floresta", "id": 16, "src": "https://images-na.ssl-images-amazon.com/images/I/81wcnNQ-TBL.jpg"},
        {"nome": "Histórias do Velho Oeste", "id": 17, "src": "https://images-na.ssl-images-amazon.com/images/I/81N7FmJhbhL.jpg"},
        {"nome": "Contos de Aventura", "id": 18, "src": "https://images-na.ssl-images-amazon.com/images/I/71HMyqG6MRL.jpg"},
        {"nome": "Explorando o Mundo", "id": 19, "src": "https://images-na.ssl-images-amazon.com/images/I/81-7N-2HCZL.jpg"},
        {"nome": "Histórias de Heróis", "id": 20, "src": "https://images-na.ssl-images-amazon.com/images/I/81zpLhP1gWL.jpg"},
        {"nome": "Viagem no Tempo", "id": 21, "src": "https://images-na.ssl-images-amazon.com/images/I/81s6DUyQCZL.jpg"},
        {"nome": "Segredos do Universo", "id": 22, "src": "https://images-na.ssl-images-amazon.com/images/I/81a4kCNuH+L.jpg"},
        {"nome": "Histórias de Mistério", "id": 23, "src": "https://images-na.ssl-images-amazon.com/images/I/81Hce0JzmLL.jpg"},
        {"nome": "Contos de Magia", "id": 24, "src": "https://images-na.ssl-images-amazon.com/images/I/81eB+7+CkUL.jpg"},
        {"nome": "Explorando a Ciência", "id": 25, "src": "https://images-na.ssl-images-amazon.com/images/I/81wcnNQ-TBL.jpg"},
        {"nome": "Histórias de Encantamento", "id": 26, "src": "https://images-na.ssl-images-amazon.com/images/I/81QpWUPzGWL.jpg"},
        {"nome": "Viagem à Lua", "id": 27, "src": "https://images-na.ssl-images-amazon.com/images/I/91HHxxtA1wL.jpg"},
        {"nome": "Segredos da Magia", "id": 28, "src": "https://images-na.ssl-images-amazon.com/images/I/71FXWMTUX7L.jpg"},
        {"nome": "Histórias de Coragem", "id": 29, "src": "https://images-na.ssl-images-amazon.com/images/I/81kAwnAh4oL.jpg"},
        {"nome": "Contos de Reis e Rainhas", "id": 30, "src": "https://images-na.ssl-images-amazon.com/images/I/81N7FmJhbhL.jpg"},
        {"nome": "Explorando a Terra", "id": 31, "src": "https://images-na.ssl-images-amazon.com/images/I/71HMyqG6MRL.jpg"},
        {"nome": "Histórias do Cotidiano", "id": 32, "src": "https://images-na.ssl-images-amazon.com/images/I/81-7N-2HCZL.jpg"},
        {"nome": "Viagem à Antártica", "id": 33, "src": "https://images-na.ssl-images-amazon.com/images/I/81zpLhP1gWL.jpg"},
        {"nome": "Segredos das Estrelas", "id": 34, "src": "https://images-na.ssl-images-amazon.com/images/I/81s6DUyQCZL.jpg"},
        {"nome": "Histórias de Superação", "id": 35, "src": "https://images-na.ssl-images-amazon.com/images/I/81a4kCNuH+L.jpg"},
        {"nome": "Contos do Folclore", "id": 36, "src": "https://images-na.ssl-images-amazon.com/images/I/81Hce0JzmLL.jpg"},
        {"nome": "Explorando os Oceanos", "id": 37, "src": "https://images-na.ssl-images-amazon.com/images/I/81eB+7+CkUL.jpg"},
        {"nome": "Histórias de Invenções", "id": 38, "src": "https://images-na.ssl-images-amazon.com/images/I/81wcnNQ-TBL.jpg"},
        {"nome": "Viagem ao Centro da Terra", "id": 39, "src": "https://images-na.ssl-images-amazon.com/images/I/81QpWUPzGWL.jpg"},
        {"nome": "Segredos do Passado", "id": 40, "src": "https://images-na.ssl-images-amazon.com/images/I/91HHxxtA1wL.jpg"},
        {"nome": "Histórias de Famosos", "id": 41, "src": "https://images-na.ssl-images-amazon.com/images/I/71FXWMTUX7L.jpg"},
        {"nome": "Contos de Pássaros", "id": 42, "src": "https://images-na.ssl-images-amazon.com/images/I/81kAwnAh4oL.jpg"},
        {"nome": "Explorando a Lua", "id": 43, "src": "https://images-na.ssl-images-amazon.com/images/I/81N7FmJhbhL.jpg"},
        {"nome": "Histórias de Sonhos", "id": 44, "src": "https://images-na.ssl-images-amazon.com/images/I/71HMyqG6MRL.jpg"},
        {"nome": "Viagem às Estrelas", "id": 45, "src": "https://images-na.ssl-images-amazon.com/images/I/81-7N-2HCZL.jpg"},
        {"nome": "Segredos da Floresta Amazônica", "id": 46, "src": "https://images-na.ssl-images-amazon.com/images/I/81zpLhP1gWL.jpg"},
        {"nome": "Histórias de Época", "id": 47, "src": "https://images-na.ssl-images-amazon.com/images/I/81s6DUyQCZL.jpg"},
        {"nome": "Contos de Gigantes", "id": 48, "src": "https://images-na.ssl-images-amazon.com/images/I/81a4kCNuH+L.jpg"},
        {"nome": "Explorando o Espaço Sideral", "id": 49, "src": "https://images-na.ssl-images-amazon.com/images/I/81Hce0JzmLL.jpg"},
        {"nome": "Histórias de Valor", "id": 50, "src": "https://images-na.ssl-images-amazon.com/images/I/81eB+7+CkUL.jpg"},
        {"nome": "Viagem ao Passado", "id": 51, "src": "https://images-na.ssl-images-amazon.com/images/I/81wcnNQ-TBL.jpg"},
        {"nome": "Segredos dos Vulcões", "id": 52, "src": "https://images-na.ssl-images-amazon.com/images/I/81QpWUPzGWL.jpg"},
        {"nome": "Histórias de Lendas", "id": 53, "src": "https://images-na.ssl-images-amazon.com/images/I/91HHxxtA1wL.jpg"},
        {"nome": "Contos de Guerreiros", "id": 54, "src": "https://images-na.ssl-images-amazon.com/images/I/71FXWMTUX7L.jpg"},
        {"nome": "Explorando as Montanhas", "id": 55, "src": "https://images-na.ssl-images-amazon.com/images/I/81kAwnAh4oL.jpg"},
        {"nome": "Histórias de Dragões", "id": 56, "src": "https://images-na.ssl-images-amazon.com/images/I/81N7FmJhbhL.jpg"},
        {"nome": "Viagem aos Confins da Terra", "id": 57, "src": "https://images-na.ssl-images-amazon.com/images/I/71HMyqG6MRL.jpg"},
        {"nome": "Segredos do Oceano Atlântico", "id": 58, "src": "https://images-na.ssl-images-amazon.com/images/I/81-7N-2HCZL.jpg"},
        {"nome": "Histórias de Mistérios Antigos", "id": 59, "src": "https://images-na.ssl-images-amazon.com/images/I/81zpLhP1gWL.jpg"},
        {"nome": "Contos de Princesas", "id": 60, "src": "https://images-na.ssl-images-amazon.com/images/I/81s6DUyQCZL.jpg"},
        {"nome": "Explorando o Mundo Antigo", "id": 61, "src": "https://images-na.ssl-images-amazon.com/images/I/81a4kCNuH+L.jpg"},
        {"nome": "Histórias de Ciência", "id": 62, "src": "https://images-na.ssl-images-amazon.com/images/I/81Hce0JzmLL.jpg"},
        {"nome": "Viagem ao Mundo Subterrâneo", "id": 63, "src": "https://images-na.ssl-images-amazon.com/images/I/81eB+7+CkUL.jpg"},
        {"nome": "Segredos do Espaço Sideral", "id": 64, "src": "https://images-na.ssl-images-amazon.com/images/I/81wcnNQ-TBL.jpg"},
        {"nome": "Histórias de Aventuras Épicas", "id": 65, "src": "https://images-na.ssl-images-amazon.com/images/I/81QpWUPzGWL.jpg"},
        {"nome": "Contos de Sabedoria", "id": 66, "src": "https://images-na.ssl-images-amazon.com/images/I/91HHxxtA1wL.jpg"},
        {"nome": "Explorando as Profundezas", "id": 67, "src": "https://images-na.ssl-images-amazon.com/images/I/71FXWMTUX7L.jpg"},
        {"nome": "Histórias de Coragem e Fé", "id": 68, "src": "https://images-na.ssl-images-amazon.com/images/I/81kAwnAh4oL.jpg"},
        {"nome": "Viagem ao Mundo dos Sonhos", "id": 69, "src": "https://images-na.ssl-images-amazon.com/images/I/81N7FmJhbhL.jpg"},
        {"nome": "Segredos das Pirâmides", "id": 70, "src": "https://images-na.ssl-images-amazon.com/images/I/71HMyqG6MRL.jpg"},
        {"nome": "Histórias de Antigos Reis", "id": 71, "src": "https://images-na.ssl-images-amazon.com/images/I/81-7N-2HCZL.jpg"},
        {"nome": "Contos de Tesouros", "id": 72, "src": "https://images-na.ssl-images-amazon.com/images/I/81zpLhP1gWL.jpg"},
        {"nome": "Explorando o Desconhecido", "id": 73, "src": "https://images-na.ssl-images-amazon.com/images/I/81s6DUyQCZL.jpg"},
        {"nome": "Histórias de Descobertas", "id": 74, "src": "https://images-na.ssl-images-amazon.com/images/I/81a4kCNuH+L.jpg"},
        {"nome": "Viagem ao Mundo Perdido", "id": 75, "src": "https://images-na.ssl-images-amazon.com/images/I/81Hce0JzmLL.jpg"},
        {"nome": "Segredos das Civilizações", "id": 76, "src": "https://images-na.ssl-images-amazon.com/images/I/81eB+7+CkUL.jpg"},
        {"nome": "Histórias de Super-heróis", "id": 77, "src": "https://images-na.ssl-images-amazon.com/images/I/81wcnNQ-TBL.jpg"},
        {"nome": "Contos de Aventuras na Terra", "id": 78, "src": "https://images-na.ssl-images-amazon.com/images/I/81QpWUPzGWL.jpg"},
        {"nome": "Explorando a Natureza", "id": 79, "src": "https://images-na.ssl-images-amazon.com/images/I/91HHxxtA1wL.jpg"},
        {"nome": "Histórias de Heróis do Espaço", "id": 80, "src": "https://images-na.ssl-images-amazon.com/images/I/71FXWMTUX7L.jpg"},
        {"nome": "Viagem ao Mundo Encantado", "id": 81, "src": "https://images-na.ssl-images-amazon.com/images/I/81kAwnAh4oL.jpg"},
        {"nome": "Segredos da História Antiga", "id": 82, "src": "https://images-na.ssl-images-amazon.com/images/I/81N7FmJhbhL.jpg"},
        {"nome": "Histórias de Superação", "id": 83, "src": "https://images-na.ssl-images-amazon.com/images/I/71HMyqG6MRL.jpg"},
        {"nome": "Contos de Grandes Exploradores", "id": 84, "src": "https://images-na.ssl-images-amazon.com/images/I/81-7N-2HCZL.jpg"},
        {"nome": "Explorando o Universo", "id": 85, "src": "https://images-na.ssl-images-amazon.com/images/I/81zpLhP1gWL.jpg"},
        {"nome": "Histórias de Guerreiros Lendários", "id": 86, "src": "https://images-na.ssl-images-amazon.com/images/I/81s6DUyQCZL.jpg"},
        {"nome": "Viagem ao Mundo dos Magos", "id": 87, "src": "https://images-na.ssl-images-amazon.com/images/I/81a4kCNuH+L.jpg"},
        {"nome": "Segredos do Antigo Egito", "id": 88, "src": "https://images-na.ssl-images-amazon.com/images/I/81Hce0JzmLL.jpg"},
        {"nome": "Histórias de Grandes Navegadores", "id": 92, "src": "https://images-na.ssl-images-amazon.com/images/I/91HHxxtA1wL.jpg"},
        {"nome": "Viagem ao Mundo dos Heróis", "id": 93, "src": "https://images-na.ssl-images-amazon.com/images/I/71FXWMTUX7L.jpg"},
        {"nome": "Segredos do Mundo Antigo", "id": 94, "src": "https://images-na.ssl-images-amazon.com/images/I/81kAwnAh4oL.jpg"},
        {"nome": "Histórias de Grandes Inventores", "id": 95, "src": "https://images-na.ssl-images-amazon.com/images/I/81N7FmJhbhL.jpg"},
        {"nome": "Contos de Aventuras no Mar", "id": 96, "src": "https://images-na.ssl-images-amazon.com/images/I/71HMyqG6MRL.jpg"},
        {"nome": "Explorando o Mundo dos Dinossauros", "id": 97, "src": "https://images-na.ssl-images-amazon.com/images/I/81-7N-2HCZL.jpg"},
        {"nome": "Histórias de Viajantes do Tempo", "id": 98, "src": "https://images-na.ssl-images-amazon.com/images/I/81zpLhP1gWL.jpg"},
        
    ]
    


